#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kringloopKleding
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="kringloopAfhaling")]
	public partial class kringloopAfhalingDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertafhaling(afhaling instance);
    partial void Updateafhaling(afhaling instance);
    partial void Deleteafhaling(afhaling instance);
    partial void Insertwoonplaatsen(woonplaatsen instance);
    partial void Updatewoonplaatsen(woonplaatsen instance);
    partial void Deletewoonplaatsen(woonplaatsen instance);
    partial void Insertverwijzers(verwijzers instance);
    partial void Updateverwijzers(verwijzers instance);
    partial void Deleteverwijzers(verwijzers instance);
    partial void Insertgezinslid(gezinslid instance);
    partial void Updategezinslid(gezinslid instance);
    partial void Deletegezinslid(gezinslid instance);
    partial void Insertgezin(gezin instance);
    partial void Updategezin(gezin instance);
    partial void Deletegezin(gezin instance);
    partial void Insertdoorverwezen(doorverwezen instance);
    partial void Updatedoorverwezen(doorverwezen instance);
    partial void Deletedoorverwezen(doorverwezen instance);
    partial void Insertinactief(inactief instance);
    partial void Updateinactief(inactief instance);
    partial void Deleteinactief(inactief instance);
    partial void Insertredenen(redenen instance);
    partial void Updateredenen(redenen instance);
    partial void Deleteredenen(redenen instance);
    #endregion
		
		public kringloopAfhalingDataContext() : 
				base(global::kringloopKleding.Properties.Settings.Default.kringloopAfhalingConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public kringloopAfhalingDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public kringloopAfhalingDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public kringloopAfhalingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public kringloopAfhalingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<afhaling> afhalings
		{
			get
			{
				return this.GetTable<afhaling>();
			}
		}
		
		public System.Data.Linq.Table<woonplaatsen> woonplaatsens
		{
			get
			{
				return this.GetTable<woonplaatsen>();
			}
		}
		
		public System.Data.Linq.Table<verwijzers> verwijzers
		{
			get
			{
				return this.GetTable<verwijzers>();
			}
		}
		
		public System.Data.Linq.Table<perMaand> perMaands
		{
			get
			{
				return this.GetTable<perMaand>();
			}
		}
		
		public System.Data.Linq.Table<gezinslid> gezinslids
		{
			get
			{
				return this.GetTable<gezinslid>();
			}
		}
		
		public System.Data.Linq.Table<registreren> registrerens
		{
			get
			{
				return this.GetTable<registreren>();
			}
		}
		
		public System.Data.Linq.Table<gezin> gezins
		{
			get
			{
				return this.GetTable<gezin>();
			}
		}
		
		public System.Data.Linq.Table<doorverwezen> doorverwezens
		{
			get
			{
				return this.GetTable<doorverwezen>();
			}
		}
		
		public System.Data.Linq.Table<inactief> inactiefs
		{
			get
			{
				return this.GetTable<inactief>();
			}
		}
		
		public System.Data.Linq.Table<redenen> redenens
		{
			get
			{
				return this.GetTable<redenen>();
			}
		}
		
		public System.Data.Linq.Table<opLeeftijd> opLeeftijds
		{
			get
			{
				return this.GetTable<opLeeftijd>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.afhaling")]
	public partial class afhaling : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.DateTime _datum;
		
		private int _gezinslid_id;
		
		private EntityRef<gezinslid> _gezinslid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndatumChanging(System.DateTime value);
    partial void OndatumChanged();
    partial void Ongezinslid_idChanging(int value);
    partial void Ongezinslid_idChanged();
    #endregion
		
		public afhaling()
		{
			this._gezinslid = default(EntityRef<gezinslid>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datum", DbType="Date NOT NULL")]
		public System.DateTime datum
		{
			get
			{
				return this._datum;
			}
			set
			{
				if ((this._datum != value))
				{
					this.OndatumChanging(value);
					this.SendPropertyChanging();
					this._datum = value;
					this.SendPropertyChanged("datum");
					this.OndatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gezinslid_id", DbType="Int NOT NULL")]
		public int gezinslid_id
		{
			get
			{
				return this._gezinslid_id;
			}
			set
			{
				if ((this._gezinslid_id != value))
				{
					if (this._gezinslid.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ongezinslid_idChanging(value);
					this.SendPropertyChanging();
					this._gezinslid_id = value;
					this.SendPropertyChanged("gezinslid_id");
					this.Ongezinslid_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gezinslid_afhaling", Storage="_gezinslid", ThisKey="gezinslid_id", OtherKey="id", IsForeignKey=true)]
		public gezinslid gezinslid
		{
			get
			{
				return this._gezinslid.Entity;
			}
			set
			{
				gezinslid previousValue = this._gezinslid.Entity;
				if (((previousValue != value) 
							|| (this._gezinslid.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._gezinslid.Entity = null;
						previousValue.afhalings.Remove(this);
					}
					this._gezinslid.Entity = value;
					if ((value != null))
					{
						value.afhalings.Add(this);
						this._gezinslid_id = value.id;
					}
					else
					{
						this._gezinslid_id = default(int);
					}
					this.SendPropertyChanged("gezinslid");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.woonplaatsen")]
	public partial class woonplaatsen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _woonplaats;
		
		private string _gemeente;
		
		private string _provincie;
		
		private EntitySet<gezin> _gezins;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnwoonplaatsChanging(string value);
    partial void OnwoonplaatsChanged();
    partial void OngemeenteChanging(string value);
    partial void OngemeenteChanged();
    partial void OnprovincieChanging(string value);
    partial void OnprovincieChanged();
    #endregion
		
		public woonplaatsen()
		{
			this._gezins = new EntitySet<gezin>(new Action<gezin>(this.attach_gezins), new Action<gezin>(this.detach_gezins));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_woonplaats", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string woonplaats
		{
			get
			{
				return this._woonplaats;
			}
			set
			{
				if ((this._woonplaats != value))
				{
					this.OnwoonplaatsChanging(value);
					this.SendPropertyChanging();
					this._woonplaats = value;
					this.SendPropertyChanged("woonplaats");
					this.OnwoonplaatsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gemeente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string gemeente
		{
			get
			{
				return this._gemeente;
			}
			set
			{
				if ((this._gemeente != value))
				{
					this.OngemeenteChanging(value);
					this.SendPropertyChanging();
					this._gemeente = value;
					this.SendPropertyChanged("gemeente");
					this.OngemeenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provincie", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string provincie
		{
			get
			{
				return this._provincie;
			}
			set
			{
				if ((this._provincie != value))
				{
					this.OnprovincieChanging(value);
					this.SendPropertyChanging();
					this._provincie = value;
					this.SendPropertyChanged("provincie");
					this.OnprovincieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="woonplaatsen_gezin", Storage="_gezins", ThisKey="woonplaats", OtherKey="woonplaats")]
		public EntitySet<gezin> gezins
		{
			get
			{
				return this._gezins;
			}
			set
			{
				this._gezins.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_gezins(gezin entity)
		{
			this.SendPropertyChanging();
			entity.woonplaatsen = this;
		}
		
		private void detach_gezins(gezin entity)
		{
			this.SendPropertyChanging();
			entity.woonplaatsen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.verwijzers")]
	public partial class verwijzers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _verwijzer;
		
		private bool _actief;
		
		private EntitySet<gezin> _gezins;
		
		private EntitySet<doorverwezen> _doorverwezens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnverwijzerChanging(string value);
    partial void OnverwijzerChanged();
    partial void OnactiefChanging(bool value);
    partial void OnactiefChanged();
    #endregion
		
		public verwijzers()
		{
			this._gezins = new EntitySet<gezin>(new Action<gezin>(this.attach_gezins), new Action<gezin>(this.detach_gezins));
			this._doorverwezens = new EntitySet<doorverwezen>(new Action<doorverwezen>(this.attach_doorverwezens), new Action<doorverwezen>(this.detach_doorverwezens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verwijzer", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string verwijzer
		{
			get
			{
				return this._verwijzer;
			}
			set
			{
				if ((this._verwijzer != value))
				{
					this.OnverwijzerChanging(value);
					this.SendPropertyChanging();
					this._verwijzer = value;
					this.SendPropertyChanged("verwijzer");
					this.OnverwijzerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actief", DbType="Bit NOT NULL")]
		public bool actief
		{
			get
			{
				return this._actief;
			}
			set
			{
				if ((this._actief != value))
				{
					this.OnactiefChanging(value);
					this.SendPropertyChanging();
					this._actief = value;
					this.SendPropertyChanged("actief");
					this.OnactiefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="verwijzers_gezin", Storage="_gezins", ThisKey="verwijzer", OtherKey="verwijzer")]
		public EntitySet<gezin> gezins
		{
			get
			{
				return this._gezins;
			}
			set
			{
				this._gezins.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="verwijzers_doorverwezen", Storage="_doorverwezens", ThisKey="verwijzer", OtherKey="naar")]
		public EntitySet<doorverwezen> doorverwezens
		{
			get
			{
				return this._doorverwezens;
			}
			set
			{
				this._doorverwezens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_gezins(gezin entity)
		{
			this.SendPropertyChanging();
			entity.verwijzers = this;
		}
		
		private void detach_gezins(gezin entity)
		{
			this.SendPropertyChanging();
			entity.verwijzers = null;
		}
		
		private void attach_doorverwezens(doorverwezen entity)
		{
			this.SendPropertyChanging();
			entity.verwijzers = this;
		}
		
		private void detach_doorverwezens(doorverwezen entity)
		{
			this.SendPropertyChanging();
			entity.verwijzers = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.perMaand")]
	public partial class perMaand
	{
		
		private System.Nullable<int> _jaar;
		
		private int _maand;
		
		private string _woonplaats;
		
		private System.Nullable<int> _gezinnen;
		
		private System.Nullable<int> _aantal;
		
		public perMaand()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jaar", DbType="Int")]
		public System.Nullable<int> jaar
		{
			get
			{
				return this._jaar;
			}
			set
			{
				if ((this._jaar != value))
				{
					this._jaar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maand", DbType="Int")]
		public int maand
		{
			get
			{
				return this._maand;
			}
			set
			{
				if ((this._maand != value))
				{
					this._maand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_woonplaats", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string woonplaats
		{
			get
			{
				return this._woonplaats;
			}
			set
			{
				if ((this._woonplaats != value))
				{
					this._woonplaats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gezinnen", DbType="Int")]
		public System.Nullable<int> gezinnen
		{
			get
			{
				return this._gezinnen;
			}
			set
			{
				if ((this._gezinnen != value))
				{
					this._gezinnen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aantal", DbType="Int")]
		public System.Nullable<int> aantal
		{
			get
			{
				return this._aantal;
			}
			set
			{
				if ((this._aantal != value))
				{
					this._aantal = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gezinslid")]
	public partial class gezinslid : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _voornaam;
		
		private decimal _geboortejaar;
		
		private int _gezin_id;
		
		private bool _actief;
		
		private string _opmerking;
		
		private EntitySet<afhaling> _afhalings;
		
		private EntitySet<inactief> _inactiefs;
		
		private EntityRef<gezin> _gezin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnvoornaamChanging(string value);
    partial void OnvoornaamChanged();
    partial void OngeboortejaarChanging(decimal value);
    partial void OngeboortejaarChanged();
    partial void Ongezin_idChanging(int value);
    partial void Ongezin_idChanged();
    partial void OnactiefChanging(bool value);
    partial void OnactiefChanged();
    partial void OnopmerkingChanging(string value);
    partial void OnopmerkingChanged();
    #endregion
		
		public gezinslid()
		{
			this._afhalings = new EntitySet<afhaling>(new Action<afhaling>(this.attach_afhalings), new Action<afhaling>(this.detach_afhalings));
			this._inactiefs = new EntitySet<inactief>(new Action<inactief>(this.attach_inactiefs), new Action<inactief>(this.detach_inactiefs));
			this._gezin = default(EntityRef<gezin>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_voornaam", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string voornaam
		{
			get
			{
				return this._voornaam;
			}
			set
			{
				if ((this._voornaam != value))
				{
					this.OnvoornaamChanging(value);
					this.SendPropertyChanging();
					this._voornaam = value;
					this.SendPropertyChanged("voornaam");
					this.OnvoornaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_geboortejaar", DbType="Decimal(4,0) NOT NULL")]
		public decimal geboortejaar
		{
			get
			{
				return this._geboortejaar;
			}
			set
			{
				if ((this._geboortejaar != value))
				{
					this.OngeboortejaarChanging(value);
					this.SendPropertyChanging();
					this._geboortejaar = value;
					this.SendPropertyChanged("geboortejaar");
					this.OngeboortejaarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gezin_id", DbType="Int NOT NULL")]
		public int gezin_id
		{
			get
			{
				return this._gezin_id;
			}
			set
			{
				if ((this._gezin_id != value))
				{
					if (this._gezin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ongezin_idChanging(value);
					this.SendPropertyChanging();
					this._gezin_id = value;
					this.SendPropertyChanged("gezin_id");
					this.Ongezin_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actief", DbType="Bit NOT NULL")]
		public bool actief
		{
			get
			{
				return this._actief;
			}
			set
			{
				if ((this._actief != value))
				{
					this.OnactiefChanging(value);
					this.SendPropertyChanging();
					this._actief = value;
					this.SendPropertyChanged("actief");
					this.OnactiefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opmerking", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string opmerking
		{
			get
			{
				return this._opmerking;
			}
			set
			{
				if ((this._opmerking != value))
				{
					this.OnopmerkingChanging(value);
					this.SendPropertyChanging();
					this._opmerking = value;
					this.SendPropertyChanged("opmerking");
					this.OnopmerkingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gezinslid_afhaling", Storage="_afhalings", ThisKey="id", OtherKey="gezinslid_id")]
		public EntitySet<afhaling> afhalings
		{
			get
			{
				return this._afhalings;
			}
			set
			{
				this._afhalings.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gezinslid_inactief", Storage="_inactiefs", ThisKey="id", OtherKey="gezinslid_id")]
		public EntitySet<inactief> inactiefs
		{
			get
			{
				return this._inactiefs;
			}
			set
			{
				this._inactiefs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gezin_gezinslid", Storage="_gezin", ThisKey="gezin_id", OtherKey="id", IsForeignKey=true)]
		public gezin gezin
		{
			get
			{
				return this._gezin.Entity;
			}
			set
			{
				gezin previousValue = this._gezin.Entity;
				if (((previousValue != value) 
							|| (this._gezin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._gezin.Entity = null;
						previousValue.gezinslids.Remove(this);
					}
					this._gezin.Entity = value;
					if ((value != null))
					{
						value.gezinslids.Add(this);
						this._gezin_id = value.id;
					}
					else
					{
						this._gezin_id = default(int);
					}
					this.SendPropertyChanged("gezin");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_afhalings(afhaling entity)
		{
			this.SendPropertyChanging();
			entity.gezinslid = this;
		}
		
		private void detach_afhalings(afhaling entity)
		{
			this.SendPropertyChanging();
			entity.gezinslid = null;
		}
		
		private void attach_inactiefs(inactief entity)
		{
			this.SendPropertyChanging();
			entity.gezinslid = this;
		}
		
		private void detach_inactiefs(inactief entity)
		{
			this.SendPropertyChanging();
			entity.gezinslid = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.registreren")]
	public partial class registreren
	{
		
		private string _naam;
		
		private decimal _geboortejaar;
		
		private System.Nullable<System.DateTime> _vorige;
		
		private string _opmerking;
		
		private int _id;
		
		private int _gezin_id;
		
		private bool _actief;
		
		public registreren()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_naam", DbType="VarChar(101) NOT NULL", CanBeNull=false)]
		public string naam
		{
			get
			{
				return this._naam;
			}
			set
			{
				if ((this._naam != value))
				{
					this._naam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_geboortejaar", DbType="Decimal(4,0) NOT NULL")]
		public decimal geboortejaar
		{
			get
			{
				return this._geboortejaar;
			}
			set
			{
				if ((this._geboortejaar != value))
				{
					this._geboortejaar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vorige", DbType="Date")]
		public System.Nullable<System.DateTime> vorige
		{
			get
			{
				return this._vorige;
			}
			set
			{
				if ((this._vorige != value))
				{
					this._vorige = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opmerking", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string opmerking
		{
			get
			{
				return this._opmerking;
			}
			set
			{
				if ((this._opmerking != value))
				{
					this._opmerking = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gezin_id", DbType="Int NOT NULL")]
		public int gezin_id
		{
			get
			{
				return this._gezin_id;
			}
			set
			{
				if ((this._gezin_id != value))
				{
					this._gezin_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actief", DbType="Bit NOT NULL")]
		public bool actief
		{
			get
			{
				return this._actief;
			}
			set
			{
				if ((this._actief != value))
				{
					this._actief = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gezin")]
	public partial class gezin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _kringloopKaartnummer;
		
		private string _achternaam;
		
		private bool _actief;
		
		private string _opmerking;
		
		private string _verwijzer;
		
		private string _woonplaats;
		
		private EntitySet<gezinslid> _gezinslids;
		
		private EntitySet<doorverwezen> _doorverwezens;
		
		private EntityRef<verwijzers> _verwijzers;
		
		private EntityRef<woonplaatsen> _woonplaatsen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnkringloopKaartnummerChanging(string value);
    partial void OnkringloopKaartnummerChanged();
    partial void OnachternaamChanging(string value);
    partial void OnachternaamChanged();
    partial void OnactiefChanging(bool value);
    partial void OnactiefChanged();
    partial void OnopmerkingChanging(string value);
    partial void OnopmerkingChanged();
    partial void OnverwijzerChanging(string value);
    partial void OnverwijzerChanged();
    partial void OnwoonplaatsChanging(string value);
    partial void OnwoonplaatsChanged();
    #endregion
		
		public gezin()
		{
			this._gezinslids = new EntitySet<gezinslid>(new Action<gezinslid>(this.attach_gezinslids), new Action<gezinslid>(this.detach_gezinslids));
			this._doorverwezens = new EntitySet<doorverwezen>(new Action<doorverwezen>(this.attach_doorverwezens), new Action<doorverwezen>(this.detach_doorverwezens));
			this._verwijzers = default(EntityRef<verwijzers>);
			this._woonplaatsen = default(EntityRef<woonplaatsen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kringloopKaartnummer", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string kringloopKaartnummer
		{
			get
			{
				return this._kringloopKaartnummer;
			}
			set
			{
				if ((this._kringloopKaartnummer != value))
				{
					this.OnkringloopKaartnummerChanging(value);
					this.SendPropertyChanging();
					this._kringloopKaartnummer = value;
					this.SendPropertyChanged("kringloopKaartnummer");
					this.OnkringloopKaartnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_achternaam", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string achternaam
		{
			get
			{
				return this._achternaam;
			}
			set
			{
				if ((this._achternaam != value))
				{
					this.OnachternaamChanging(value);
					this.SendPropertyChanging();
					this._achternaam = value;
					this.SendPropertyChanged("achternaam");
					this.OnachternaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actief", DbType="Bit NOT NULL")]
		public bool actief
		{
			get
			{
				return this._actief;
			}
			set
			{
				if ((this._actief != value))
				{
					this.OnactiefChanging(value);
					this.SendPropertyChanging();
					this._actief = value;
					this.SendPropertyChanged("actief");
					this.OnactiefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opmerking", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string opmerking
		{
			get
			{
				return this._opmerking;
			}
			set
			{
				if ((this._opmerking != value))
				{
					this.OnopmerkingChanging(value);
					this.SendPropertyChanging();
					this._opmerking = value;
					this.SendPropertyChanged("opmerking");
					this.OnopmerkingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verwijzer", DbType="VarChar(30)")]
		public string verwijzer
		{
			get
			{
				return this._verwijzer;
			}
			set
			{
				if ((this._verwijzer != value))
				{
					if (this._verwijzers.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnverwijzerChanging(value);
					this.SendPropertyChanging();
					this._verwijzer = value;
					this.SendPropertyChanged("verwijzer");
					this.OnverwijzerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_woonplaats", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string woonplaats
		{
			get
			{
				return this._woonplaats;
			}
			set
			{
				if ((this._woonplaats != value))
				{
					if (this._woonplaatsen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnwoonplaatsChanging(value);
					this.SendPropertyChanging();
					this._woonplaats = value;
					this.SendPropertyChanged("woonplaats");
					this.OnwoonplaatsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gezin_gezinslid", Storage="_gezinslids", ThisKey="id", OtherKey="gezin_id")]
		public EntitySet<gezinslid> gezinslids
		{
			get
			{
				return this._gezinslids;
			}
			set
			{
				this._gezinslids.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gezin_doorverwezen", Storage="_doorverwezens", ThisKey="id", OtherKey="gezin_id")]
		public EntitySet<doorverwezen> doorverwezens
		{
			get
			{
				return this._doorverwezens;
			}
			set
			{
				this._doorverwezens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="verwijzers_gezin", Storage="_verwijzers", ThisKey="verwijzer", OtherKey="verwijzer", IsForeignKey=true)]
		public verwijzers verwijzers
		{
			get
			{
				return this._verwijzers.Entity;
			}
			set
			{
				verwijzers previousValue = this._verwijzers.Entity;
				if (((previousValue != value) 
							|| (this._verwijzers.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._verwijzers.Entity = null;
						previousValue.gezins.Remove(this);
					}
					this._verwijzers.Entity = value;
					if ((value != null))
					{
						value.gezins.Add(this);
						this._verwijzer = value.verwijzer;
					}
					else
					{
						this._verwijzer = default(string);
					}
					this.SendPropertyChanged("verwijzers");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="woonplaatsen_gezin", Storage="_woonplaatsen", ThisKey="woonplaats", OtherKey="woonplaats", IsForeignKey=true)]
		public woonplaatsen woonplaatsen
		{
			get
			{
				return this._woonplaatsen.Entity;
			}
			set
			{
				woonplaatsen previousValue = this._woonplaatsen.Entity;
				if (((previousValue != value) 
							|| (this._woonplaatsen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._woonplaatsen.Entity = null;
						previousValue.gezins.Remove(this);
					}
					this._woonplaatsen.Entity = value;
					if ((value != null))
					{
						value.gezins.Add(this);
						this._woonplaats = value.woonplaats;
					}
					else
					{
						this._woonplaats = default(string);
					}
					this.SendPropertyChanged("woonplaatsen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_gezinslids(gezinslid entity)
		{
			this.SendPropertyChanging();
			entity.gezin = this;
		}
		
		private void detach_gezinslids(gezinslid entity)
		{
			this.SendPropertyChanging();
			entity.gezin = null;
		}
		
		private void attach_doorverwezens(doorverwezen entity)
		{
			this.SendPropertyChanging();
			entity.gezin = this;
		}
		
		private void detach_doorverwezens(doorverwezen entity)
		{
			this.SendPropertyChanging();
			entity.gezin = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.doorverwezen")]
	public partial class doorverwezen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _naar;
		
		private System.DateTime _datum;
		
		private int _gezin_id;
		
		private EntityRef<verwijzers> _verwijzers;
		
		private EntityRef<gezin> _gezin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnaarChanging(string value);
    partial void OnnaarChanged();
    partial void OndatumChanging(System.DateTime value);
    partial void OndatumChanged();
    partial void Ongezin_idChanging(int value);
    partial void Ongezin_idChanged();
    #endregion
		
		public doorverwezen()
		{
			this._verwijzers = default(EntityRef<verwijzers>);
			this._gezin = default(EntityRef<gezin>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_naar", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string naar
		{
			get
			{
				return this._naar;
			}
			set
			{
				if ((this._naar != value))
				{
					if (this._verwijzers.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnaarChanging(value);
					this.SendPropertyChanging();
					this._naar = value;
					this.SendPropertyChanged("naar");
					this.OnnaarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datum", DbType="Date NOT NULL")]
		public System.DateTime datum
		{
			get
			{
				return this._datum;
			}
			set
			{
				if ((this._datum != value))
				{
					this.OndatumChanging(value);
					this.SendPropertyChanging();
					this._datum = value;
					this.SendPropertyChanged("datum");
					this.OndatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gezin_id", DbType="Int NOT NULL")]
		public int gezin_id
		{
			get
			{
				return this._gezin_id;
			}
			set
			{
				if ((this._gezin_id != value))
				{
					if (this._gezin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ongezin_idChanging(value);
					this.SendPropertyChanging();
					this._gezin_id = value;
					this.SendPropertyChanged("gezin_id");
					this.Ongezin_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="verwijzers_doorverwezen", Storage="_verwijzers", ThisKey="naar", OtherKey="verwijzer", IsForeignKey=true)]
		public verwijzers verwijzers
		{
			get
			{
				return this._verwijzers.Entity;
			}
			set
			{
				verwijzers previousValue = this._verwijzers.Entity;
				if (((previousValue != value) 
							|| (this._verwijzers.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._verwijzers.Entity = null;
						previousValue.doorverwezens.Remove(this);
					}
					this._verwijzers.Entity = value;
					if ((value != null))
					{
						value.doorverwezens.Add(this);
						this._naar = value.verwijzer;
					}
					else
					{
						this._naar = default(string);
					}
					this.SendPropertyChanged("verwijzers");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gezin_doorverwezen", Storage="_gezin", ThisKey="gezin_id", OtherKey="id", IsForeignKey=true)]
		public gezin gezin
		{
			get
			{
				return this._gezin.Entity;
			}
			set
			{
				gezin previousValue = this._gezin.Entity;
				if (((previousValue != value) 
							|| (this._gezin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._gezin.Entity = null;
						previousValue.doorverwezens.Remove(this);
					}
					this._gezin.Entity = value;
					if ((value != null))
					{
						value.doorverwezens.Add(this);
						this._gezin_id = value.id;
					}
					else
					{
						this._gezin_id = default(int);
					}
					this.SendPropertyChanged("gezin");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.inactief")]
	public partial class inactief : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _gezinslid_id;
		
		private System.DateTime _datum;
		
		private string _reden;
		
		private EntityRef<gezinslid> _gezinslid;
		
		private EntityRef<redenen> _redenen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ongezinslid_idChanging(System.Nullable<int> value);
    partial void Ongezinslid_idChanged();
    partial void OndatumChanging(System.DateTime value);
    partial void OndatumChanged();
    partial void OnredenChanging(string value);
    partial void OnredenChanged();
    #endregion
		
		public inactief()
		{
			this._gezinslid = default(EntityRef<gezinslid>);
			this._redenen = default(EntityRef<redenen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gezinslid_id", DbType="Int")]
		public System.Nullable<int> gezinslid_id
		{
			get
			{
				return this._gezinslid_id;
			}
			set
			{
				if ((this._gezinslid_id != value))
				{
					if (this._gezinslid.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ongezinslid_idChanging(value);
					this.SendPropertyChanging();
					this._gezinslid_id = value;
					this.SendPropertyChanged("gezinslid_id");
					this.Ongezinslid_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datum", DbType="Date NOT NULL")]
		public System.DateTime datum
		{
			get
			{
				return this._datum;
			}
			set
			{
				if ((this._datum != value))
				{
					this.OndatumChanging(value);
					this.SendPropertyChanging();
					this._datum = value;
					this.SendPropertyChanged("datum");
					this.OndatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reden", DbType="VarChar(30)")]
		public string reden
		{
			get
			{
				return this._reden;
			}
			set
			{
				if ((this._reden != value))
				{
					if (this._redenen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnredenChanging(value);
					this.SendPropertyChanging();
					this._reden = value;
					this.SendPropertyChanged("reden");
					this.OnredenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gezinslid_inactief", Storage="_gezinslid", ThisKey="gezinslid_id", OtherKey="id", IsForeignKey=true)]
		public gezinslid gezinslid
		{
			get
			{
				return this._gezinslid.Entity;
			}
			set
			{
				gezinslid previousValue = this._gezinslid.Entity;
				if (((previousValue != value) 
							|| (this._gezinslid.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._gezinslid.Entity = null;
						previousValue.inactiefs.Remove(this);
					}
					this._gezinslid.Entity = value;
					if ((value != null))
					{
						value.inactiefs.Add(this);
						this._gezinslid_id = value.id;
					}
					else
					{
						this._gezinslid_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("gezinslid");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="redenen_inactief", Storage="_redenen", ThisKey="reden", OtherKey="reden", IsForeignKey=true)]
		public redenen redenen
		{
			get
			{
				return this._redenen.Entity;
			}
			set
			{
				redenen previousValue = this._redenen.Entity;
				if (((previousValue != value) 
							|| (this._redenen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._redenen.Entity = null;
						previousValue.inactiefs.Remove(this);
					}
					this._redenen.Entity = value;
					if ((value != null))
					{
						value.inactiefs.Add(this);
						this._reden = value.reden;
					}
					else
					{
						this._reden = default(string);
					}
					this.SendPropertyChanged("redenen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.redenen")]
	public partial class redenen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _reden;
		
		private EntitySet<inactief> _inactiefs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnredenChanging(string value);
    partial void OnredenChanged();
    #endregion
		
		public redenen()
		{
			this._inactiefs = new EntitySet<inactief>(new Action<inactief>(this.attach_inactiefs), new Action<inactief>(this.detach_inactiefs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reden", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string reden
		{
			get
			{
				return this._reden;
			}
			set
			{
				if ((this._reden != value))
				{
					this.OnredenChanging(value);
					this.SendPropertyChanging();
					this._reden = value;
					this.SendPropertyChanged("reden");
					this.OnredenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="redenen_inactief", Storage="_inactiefs", ThisKey="reden", OtherKey="reden")]
		public EntitySet<inactief> inactiefs
		{
			get
			{
				return this._inactiefs;
			}
			set
			{
				this._inactiefs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_inactiefs(inactief entity)
		{
			this.SendPropertyChanging();
			entity.redenen = this;
		}
		
		private void detach_inactiefs(inactief entity)
		{
			this.SendPropertyChanging();
			entity.redenen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.opLeeftijd")]
	public partial class opLeeftijd
	{
		
		private System.Nullable<int> _jaar;
		
		private int _maand;
		
		private string _woonplaats;
		
		private System.Nullable<decimal> _leeftijdsgroep;
		
		private System.Nullable<int> _aantal;
		
		public opLeeftijd()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jaar", DbType="Int")]
		public System.Nullable<int> jaar
		{
			get
			{
				return this._jaar;
			}
			set
			{
				if ((this._jaar != value))
				{
					this._jaar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maand", DbType="Int")]
		public int maand
		{
			get
			{
				return this._maand;
			}
			set
			{
				if ((this._maand != value))
				{
					this._maand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_woonplaats", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string woonplaats
		{
			get
			{
				return this._woonplaats;
			}
			set
			{
				if ((this._woonplaats != value))
				{
					this._woonplaats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leeftijdsgroep", DbType="Decimal(11,0)")]
		public System.Nullable<decimal> leeftijdsgroep
		{
			get
			{
				return this._leeftijdsgroep;
			}
			set
			{
				if ((this._leeftijdsgroep != value))
				{
					this._leeftijdsgroep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aantal", DbType="Int")]
		public System.Nullable<int> aantal
		{
			get
			{
				return this._aantal;
			}
			set
			{
				if ((this._aantal != value))
				{
					this._aantal = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
